using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// A chunk is a cubic structure of fixed side that contains individual blocks.
/// Chunks are generated by the TerrainGenerator.
/// </summary>
public class Chunk : MonoBehaviour
{	
	// The blocks contained within the current chunk.
    private List<Block> blocks;

	[SerializeField] private int chunkSize = 16;

	private int _x;
	private int _y;

	/// <summary>
	/// The x-position in the world's 2D plane of the chunk.
	/// </summary>
	public int x { get; }

	/// <summary>
	/// The y-position in the world's 2D plane of the chunk.
	/// </summary>
	public int y { get; }
}
